# yaml-language-server: $schema=../../api/jsonschema/harp.bundle.v1/Patch.json
apiVersion: harp.zntr.io/v2
kind: BundlePatch
meta:
  name: "selective-encryption"
  description: "Apply annotation to enable partial encryption"
spec:
  rules:
  - selector:
      matchPath:
        regex: "^doorbell/auth/ldap/tls"
    package:
      annotations:
        add:
          harp.zntr.io/v2/package#encryptionKeyAlias: security

